### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rocwind** [shm-open/code-push-server#123]
- [ ]  (WIP) refactor to ts
- [ ]  add detailed logging for production
- [ ]  test coverage
- [ ]  simplify Promise based code (async - await)
